### ISSUE TITLE
`python3-websockify` dependencies not installed

### ISSUE THREAD

**Issue by ylei-tsubame** [ClusterLabs/anvil-external-deps#3]
The `python3-websockify` package itself installs without issues (non-EPEL dependencies are already present), but it doesn't function correctly:
```
$ websockify --help
Traceback (most recent call last):
  File "/usr/bin/websockify", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'simplejson' distribution was not found and is required by websockify
```

`dnf` shows the correct dependencies **after** `dnf install epel-release`:
* `python3-simplejson`
* `python3-redis`
* `python3-jwcrypto` (which requires enabling module stream `idm`)
* `python3-numpy` (which requires `libgfortran`, `libquadmath`, `openblas`, and `openblas-threads`)

**Note**: dependencies above are specified in the `setup.py` within the sources, not the spec file.

Workarounds I've tried that doesn't work:
* Add `epel-release` as a dependency to one of 1) `anvil-core`, or 2) `anvil-node` and `anvil-dr`. This method failed because `epel-release` isn't installed prior to the dependency resolution for installing `anvil-core` and either `anvil-node` or `anvil-dr`. `dnf` resolves all dependencies before installation, meaning `epel-release` must be installed before the dependency resolution to make the correct dependencies visible.
* Add `dnf install epel-release` to the `%pre` section and `dnf remove epel-release` to the `%post` section for `anvil-node` and `anvil-dr`. This method failed because it instructs `dnf` to do a nested installation which causes a deadlock.

**Note**: this issue has not been tested on a freshly installed system; not sure if it only happens on the system I'm using.

May I get some direction(s) on how to solve this?

**Comment by fabbione** [comment]
I see the issue it´s in the internal repo build system. No we shouldn´t enable epel, but rather fix the build problem.

From anvil repo:
$ rpm -qp ./python3-websockify-0.11.0-1.el8.noarch.rpm --requires
/usr/libexec/platform-python
python(abi) = 3.6
python3-setuptools
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PartialHardlinkSets) <= 4.0.4-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1

From EPEL:
$ rpm -qp ./python3-websockify-0.11.0-1.el8.noarch.rpm --requires
/usr/bin/python3.6
python(abi) = 3.6
python3-setuptools
python3.6dist(jwcrypto)
python3.6dist(numpy)
python3.6dist(redis)
python3.6dist(requests)
python3.6dist(simplejson)
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PartialHardlinkSets) <= 4.0.4-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1

I am fairly confident this has something to do with the build environment as we are building the exact same srpm/spec file as EPEL.

I am investigating why the anvil build is not calculating the dependencies correctly.

**Comment by fabbione** [comment]
Confirmed, the issue is somewhat in our build environment. I am looking into a proper fix.

**Comment by fabbione** [comment]
I have isolated the issue and working on a fix.

**Comment by fabbione** [comment]
This is now solved for the CI repositories

**Comment by ylei-tsubame** [comment]
Thanks for the quick fix!
